git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

addons:
  sonarcloud:
    organization: "aymrick"
    token: "$SONARCLOUD_TOKEN"

jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - echo "Maven build"
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Aymrick_sample-application-students
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - docker build -t aymrick/sample-backend .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push aymrick/sample-backend
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - docker build -t aymrick/sample-frontend .
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker push aymrick/sample-frontend
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

services:
  - docker