git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
    - stage: "Build and Test"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
      script:
        - echo "Maven build"
        - echo "Run test coverage and Quality Gate"
    - stage: "Build and Test"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
      script:
        - echo "NPM install and build"
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - docker-compose build
        - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
        - docker push aymrick/devops-sample-app
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - docker-compose build
        - docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
        - docker push aymrick/devops-sample-app
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"

services:
  - docker